FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

COPY pyproject.toml .
RUN pip install ".[train]"

RUN pip install boto3

COPY src/build_model /app/src/build_model
COPY src/utils /app/src/utils
COPY datasets/raw /app/datasets/raw

CMD [ "bash" ]