# data.yml
# Data paths
main_data_path: datasets/raw/car_price.csv

# Target
target: price

# Features
features:
  - mileage
  - tax
  - mpg
  - engineSize
  - model
  - transmission
  - fuelType
  - Make
  - year

# Numerical Features
num_cols: 
  - mileage
  - tax
  - mpg
  - engineSize

# Categorical Features
cat_cols:
  - model
  - transmission
  - fuelType
  - Make

date_cols:
  - year

# Train/Test split
split:
  test_size: 0.2
  splitting_random_state: 101

# Rare labesl
rare_label:
  tol: 0.001
  variables:
    - model